FROM node:18 AS builder

# Fix for react-scripts 4 with Node 18+
ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /home/node/bc

COPY package*.json ./

RUN npm install

COPY .env ./
COPY tsconfig.json ./
COPY src ./src
COPY typings ./typings
COPY public ./public
COPY vcs ./vcs

RUN npm run build

FROM nginx AS http

COPY --from=builder  /home/node/bc/build /var/www/html
COPY ./nginx-config/default.conf /etc/nginx/conf.d/default.conf
