name: "SCAN: Snyk Security Scanning (On Push to Stable)"

on:
  push:
    branches:
      - stable

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk + snyk-to-html
        run: npm install -g snyk snyk-to-html

      # SCA scan (dependencies)
      - name: Run Snyk dependency-SCA Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --fail-on-severity=high --json | snyk-to-html -o snyk_brokencrystals_sca.html

      # SAST scan (code)
      - name: Run Snyk Code Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --fail-on-severity=high --json | snyk-to-html -o snyk_brokencrystals_sast.html

      - name: Upload results to Github Code Scanning
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk_brokencrystals_sca.html
            snyk_brokencrystals_sast.html
